### ISSUE TITLE
not work now, it seems updated; no firmware selection now 

### ISSUE THREAD

**Issue by monkeycraps** [kioipp/bose_earbuds_firmware#1]
![image](https://user-images.githubusercontent.com/2322555/141865641-07ab912c-d738-4eae-8ddd-37265b517383.png)
![image](https://user-images.githubusercontent.com/2322555/141865739-cfabd6c0-d6bb-4e1d-8218-f9b304c89c77.png)

**Comment by monkeycraps** [comment]
old version 6.xxxx can not be launched at website

**Comment by monkeycraps** [comment]
![image](https://user-images.githubusercontent.com/2322555/141870342-f97db68b-82de-4043-a8b4-98d8d56f6ef9.png)

**Comment by kioipp** [comment]
@monkeycraps Try to upgrade Bose updater to latest version ( I remember it's like 7.xxxxx).

**Comment by monkeycraps** [comment]
> @monkeycraps Try to upgrade Bose updater to latest version ( I remember it's like 7.xxxxx).

@kioipp should i donwload latest version from the office website ? 
does it worked for that version ? 
i checked repository bosefirmware/ced. i should use the edtied bose updater 
![image](https://user-images.githubusercontent.com/2322555/143258072-58d7ed6a-68b0-4aed-b956-a68658518b9a.png)

**Comment by monkeycraps** [comment]
not work for mac os now, finally i downgrade it at windows system
