### ISSUE TITLE
any index files for other versions?

### ISSUE THREAD

**Issue by Thenorthernsea** [kioipp/bose_earbuds_firmware#2]

**Comment by kioipp** [comment]
@Thenorthernsea You can create your index file for QC earbuds once you have the version string.
For me, I first found 1.0.7 is `1.0.7-xxxxx+620b71c`, so I try to create the download URL from current version 2.0.7. Here is my steps:

## Download the bin file
From official index.html:
```xml
<INDEX REVISION="01.00.00">
<DEVICE ID="0x402F" PRODUCTNAME="Quietcomfort Earbuds" USE_CLOUD="0">
<HARDWARE REVISION="01.00.00">
<RELEASE HTTPHOST="www.bose.cn" LANGUAGES="en-us,es-mx,de,it,fr,zh-cn,nl,ja,pt-br,ru,pl" REVISION="2.0.7-fb87694" URLPATH="/ced/bose_music_china/lando/">
<IMAGE CRC="0xFCFF86A2" FILENAME="lando_2x1_rom_spin_encrypted_prod_2.0.7-fb87694.bin" LENGTH="6350682" NOFORCE="1" REVISION="2.0.7-fb87694" SUBID="0"/>
</RELEASE>
</HARDWARE>
</DEVICE>
</INDEX>
```
So I guess the 2.0.7 bin is , it did work:
`https://www.bose.cn/ced/bose_music_china/lando/lando_2x1_rom_spin_encrypted_prod_2.0.7-fb87694.bin`

Then I replace the 1.0.7 string, the URL works too:
`https://www.bose.cn/ced/bose_music_china/lando/lando_2x1_rom_spin_encrypted_prod_1.0.7-620b71c.bin`

## Get the CRC and length
Once bin file is downloaded, file length and CRC value will be calucated:

```bash
# Get file length
ls -l lando_2x1_rom_spin_encrypted_prod_1.0.7-620b71c.bin
-rw-r--r--@ 1 root  root  6341544 Nov 16 19:07 lando_2x1_rom_spin_encrypted_prod_1.0.7-620b71c.bin

# Get file CRC
crc32 lando_2x1_rom_spin_encrypted_prod_1.0.7-620b71c.bin
7cf57460
```

## Fill index html with your own version
Fill the field in index file as needed: [index.html](https://github.com/kioipp/bose_earbuds_firmware/blob/main/index.xml)

**Comment by Thenorthernsea** [comment]
> @Thenorthernsea You can create your index file for QC earbuds once you have the version string. For me, I first found 1.0.7 is `1.0.7-xxxxx+620b71c`, so I try to create the download URL from current version 2.0.7. Here is my steps:
> 
> ## Download the bin file
> From official index.html:
> 
> ```
> <INDEX REVISION="01.00.00">
> <DEVICE ID="0x402F" PRODUCTNAME="Quietcomfort Earbuds" USE_CLOUD="0">
> <HARDWARE REVISION="01.00.00">
> <RELEASE HTTPHOST="www.bose.cn" LANGUAGES="en-us,es-mx,de,it,fr,zh-cn,nl,ja,pt-br,ru,pl" REVISION="2.0.7-fb87694" URLPATH="/ced/bose_music_china/lando/">
> <IMAGE CRC="0xFCFF86A2" FILENAME="lando_2x1_rom_spin_encrypted_prod_2.0.7-fb87694.bin" LENGTH="6350682" NOFORCE="1" REVISION="2.0.7-fb87694" SUBID="0"/>
> </RELEASE>
> </HARDWARE>
> </DEVICE>
> </INDEX>
> ```
> 
> So I guess the 2.0.7 bin is , it did work: `https://www.bose.cn/ced/bose_music_china/lando/lando_2x1_rom_spin_encrypted_prod_2.0.7-fb87694.bin`
> 
> Then I replace the 1.0.7 string, the URL works too: `https://www.bose.cn/ced/bose_music_china/lando/lando_2x1_rom_spin_encrypted_prod_1.0.7-620b71c.bin`
> 
> ## Get the CRC and length
> Once bin file is downloaded, file length and CRC value will be calucated:
> 
> ```shell
> # Get file length
> ls -l lando_2x1_rom_spin_encrypted_prod_1.0.7-620b71c.bin
> -rw-r--r--@ 1 root  root  6341544 Nov 16 19:07 lando_2x1_rom_spin_encrypted_prod_1.0.7-620b71c.bin
> 
> # Get file CRC
> crc32 lando_2x1_rom_spin_encrypted_prod_1.0.7-620b71c.bin
> 7cf57460
> ```
> 
> ## Fill index html with your own version
> Fill the field in index file as needed: [index.html](https://github.com/kioipp/bose_earbuds_firmware/blob/main/index.xml)

It seems that you can't use the bose updater application to install the latest 2.0.7 firmware.

**Comment by kioipp** [comment]
> > @Thenorthernsea You can create your index file for QC earbuds once you have the version string. For me, I first found 1.0.7 is `1.0.7-xxxxx+620b71c`, so I try to create the download URL from current version 2.0.7. Here is my steps:
> > ## Download the bin file
> > From official index.html:
> > ```
> > <INDEX REVISION="01.00.00">
> > <DEVICE ID="0x402F" PRODUCTNAME="Quietcomfort Earbuds" USE_CLOUD="0">
> > <HARDWARE REVISION="01.00.00">
> > <RELEASE HTTPHOST="www.bose.cn" LANGUAGES="en-us,es-mx,de,it,fr,zh-cn,nl,ja,pt-br,ru,pl" REVISION="2.0.7-fb87694" URLPATH="/ced/bose_music_china/lando/">
> > <IMAGE CRC="0xFCFF86A2" FILENAME="lando_2x1_rom_spin_encrypted_prod_2.0.7-fb87694.bin" LENGTH="6350682" NOFORCE="1" REVISION="2.0.7-fb87694" SUBID="0"/>
> > </RELEASE>
> > </HARDWARE>
> > </DEVICE>
> > </INDEX>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So I guess the 2.0.7 bin is , it did work: `https://www.bose.cn/ced/bose_music_china/lando/lando_2x1_rom_spin_encrypted_prod_2.0.7-fb87694.bin`
> > Then I replace the 1.0.7 string, the URL works too: `https://www.bose.cn/ced/bose_music_china/lando/lando_2x1_rom_spin_encrypted_prod_1.0.7-620b71c.bin`
> > ## Get the CRC and length
> > Once bin file is downloaded, file length and CRC value will be calucated:
> > ```shell
> > # Get file length
> > ls -l lando_2x1_rom_spin_encrypted_prod_1.0.7-620b71c.bin
> > -rw-r--r--@ 1 root  root  6341544 Nov 16 19:07 lando_2x1_rom_spin_encrypted_prod_1.0.7-620b71c.bin
> > 
> > # Get file CRC
> > crc32 lando_2x1_rom_spin_encrypted_prod_1.0.7-620b71c.bin
> > 7cf57460
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## Fill index html with your own version
> > Fill the field in index file as needed: [index.html](https://github.com/kioipp/bose_earbuds_firmware/blob/main/index.xml)
> 
> It seems that you can't use the bose updater application to install the latest 2.0.7 firmware.

- Merge 2.0.7 index content;
- Use official index content;

The two ways could install the latest firmware either.

**Comment by Thenorthernsea** [comment]
> > > @Thenorthernsea You can create your index file for QC earbuds once you have the version string. For me, I first found 1.0.7 is `1.0.7-xxxxx+620b71c`, so I try to create the download URL from current version 2.0.7. Here is my steps:
> > > ## Download the bin file
> > > From official index.html:
> > > ```
> > > <INDEX REVISION="01.00.00">
> > > <DEVICE ID="0x402F" PRODUCTNAME="Quietcomfort Earbuds" USE_CLOUD="0">
> > > <HARDWARE REVISION="01.00.00">
> > > <RELEASE HTTPHOST="www.bose.cn" LANGUAGES="en-us,es-mx,de,it,fr,zh-cn,nl,ja,pt-br,ru,pl" REVISION="2.0.7-fb87694" URLPATH="/ced/bose_music_china/lando/">
> > > <IMAGE CRC="0xFCFF86A2" FILENAME="lando_2x1_rom_spin_encrypted_prod_2.0.7-fb87694.bin" LENGTH="6350682" NOFORCE="1" REVISION="2.0.7-fb87694" SUBID="0"/>
> > > </RELEASE>
> > > </HARDWARE>
> > > </DEVICE>
> > > </INDEX>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > So I guess the 2.0.7 bin is , it did work: `https://www.bose.cn/ced/bose_music_china/lando/lando_2x1_rom_spin_encrypted_prod_2.0.7-fb87694.bin`
> > > Then I replace the 1.0.7 string, the URL works too: `https://www.bose.cn/ced/bose_music_china/lando/lando_2x1_rom_spin_encrypted_prod_1.0.7-620b71c.bin`
> > > ## Get the CRC and length
> > > Once bin file is downloaded, file length and CRC value will be calucated:
> > > ```shell
> > > # Get file length
> > > ls -l lando_2x1_rom_spin_encrypted_prod_1.0.7-620b71c.bin
> > > -rw-r--r--@ 1 root  root  6341544 Nov 16 19:07 lando_2x1_rom_spin_encrypted_prod_1.0.7-620b71c.bin
> > > 
> > > # Get file CRC
> > > crc32 lando_2x1_rom_spin_encrypted_prod_1.0.7-620b71c.bin
> > > 7cf57460
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ## Fill index html with your own version
> > > Fill the field in index file as needed: [index.html](https://github.com/kioipp/bose_earbuds_firmware/blob/main/index.xml)
> > 
> > 
> > It seems that you can't use the bose updater application to install the latest 2.0.7 firmware.
> 
> * Merge 2.0.7 index content;
> * Use official index content;
> 
> The two ways could install the latest firmware either.

I tried. the log says "update failed".
however the 1.0.7 firmware can be installed.

**Comment by 1584598022** [comment]
I found there is a error in the official index , the length of the 2.07 firmware is 6534306, but the index shows it 6350682 as it is the length of 1.27 firmware. so that is why it doesn't work.

**Comment by 1584598022** [comment]
> 

I found there is a error in the official index , the length of the 2.07 firmware is 6534306, but the index shows it 6350682 as it is the length of 1.27. So that is why  it does't work.

**Comment by 1584598022** [comment]
> > > > @Thenorthernsea You can create your index file for QC earbuds once you have the version string. For me, I first found 1.0.7 is `1.0.7-xxxxx+620b71c`, so I try to create the download URL from current version 2.0.7. Here is my steps:
> > > > ## Download the bin file
> > > > From official index.html:
> > > > ```
> > > > <INDEX REVISION="01.00.00">
> > > > <DEVICE ID="0x402F" PRODUCTNAME="Quietcomfort Earbuds" USE_CLOUD="0">
> > > > <HARDWARE REVISION="01.00.00">
> > > > <RELEASE HTTPHOST="www.bose.cn" LANGUAGES="en-us,es-mx,de,it,fr,zh-cn,nl,ja,pt-br,ru,pl" REVISION="2.0.7-fb87694" URLPATH="/ced/bose_music_china/lando/">
> > > > <IMAGE CRC="0xFCFF86A2" FILENAME="lando_2x1_rom_spin_encrypted_prod_2.0.7-fb87694.bin" LENGTH="6350682" NOFORCE="1" REVISION="2.0.7-fb87694" SUBID="0"/>
> > > > </RELEASE>
> > > > </HARDWARE>
> > > > </DEVICE>
> > > > </INDEX>
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > So I guess the 2.0.7 bin is , it did work: `https://www.bose.cn/ced/bose_music_china/lando/lando_2x1_rom_spin_encrypted_prod_2.0.7-fb87694.bin`
> > > > Then I replace the 1.0.7 string, the URL works too: `https://www.bose.cn/ced/bose_music_china/lando/lando_2x1_rom_spin_encrypted_prod_1.0.7-620b71c.bin`
> > > > ## Get the CRC and length
> > > > Once bin file is downloaded, file length and CRC value will be calucated:
> > > > ```shell
> > > > # Get file length
> > > > ls -l lando_2x1_rom_spin_encrypted_prod_1.0.7-620b71c.bin
> > > > -rw-r--r--@ 1 root  root  6341544 Nov 16 19:07 lando_2x1_rom_spin_encrypted_prod_1.0.7-620b71c.bin
> > > > 
> > > > # Get file CRC
> > > > crc32 lando_2x1_rom_spin_encrypted_prod_1.0.7-620b71c.bin
> > > > 7cf57460
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ## Fill index html with your own version
> > > > Fill the field in index file as needed: [index.html](https://github.com/kioipp/bose_earbuds_firmware/blob/main/index.xml)
> > > 
> > > 
> > > It seems that you can't use the bose updater application to install the latest 2.0.7 firmware.
> > 
> > 
> > 
> > * Merge 2.0.7 index content;
> > * Use official index content;
> > 
> > The two ways could install the latest firmware either.
> 
> I tried. the log says "update failed". however the 1.0.7 firmware can be installed.

I found there is a error in the official index , the length of the 2.07 firmware is 6534306, but the index shows it 6350682 as it is the length of 1.27. So that is why  it does't work.

**Comment by Thenorthernsea** [comment]
> > > > > @Thenorthernsea You can create your index file for QC earbuds once you have the version string. For me, I first found 1.0.7 is `1.0.7-xxxxx+620b71c`, so I try to create the download URL from current version 2.0.7. Here is my steps:
> > > > > ## Download the bin file
> > > > > From official index.html:
> > > > > ```
> > > > > <INDEX REVISION="01.00.00">
> > > > > <DEVICE ID="0x402F" PRODUCTNAME="Quietcomfort Earbuds" USE_CLOUD="0">
> > > > > <HARDWARE REVISION="01.00.00">
> > > > > <RELEASE HTTPHOST="www.bose.cn" LANGUAGES="en-us,es-mx,de,it,fr,zh-cn,nl,ja,pt-br,ru,pl" REVISION="2.0.7-fb87694" URLPATH="/ced/bose_music_china/lando/">
> > > > > <IMAGE CRC="0xFCFF86A2" FILENAME="lando_2x1_rom_spin_encrypted_prod_2.0.7-fb87694.bin" LENGTH="6350682" NOFORCE="1" REVISION="2.0.7-fb87694" SUBID="0"/>
> > > > > </RELEASE>
> > > > > </HARDWARE>
> > > > > </DEVICE>
> > > > > </INDEX>
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > So I guess the 2.0.7 bin is , it did work: `https://www.bose.cn/ced/bose_music_china/lando/lando_2x1_rom_spin_encrypted_prod_2.0.7-fb87694.bin`
> > > > > Then I replace the 1.0.7 string, the URL works too: `https://www.bose.cn/ced/bose_music_china/lando/lando_2x1_rom_spin_encrypted_prod_1.0.7-620b71c.bin`
> > > > > ## Get the CRC and length
> > > > > Once bin file is downloaded, file length and CRC value will be calucated:
> > > > > ```shell
> > > > > # Get file length
> > > > > ls -l lando_2x1_rom_spin_encrypted_prod_1.0.7-620b71c.bin
> > > > > -rw-r--r--@ 1 root  root  6341544 Nov 16 19:07 lando_2x1_rom_spin_encrypted_prod_1.0.7-620b71c.bin
> > > > > 
> > > > > # Get file CRC
> > > > > crc32 lando_2x1_rom_spin_encrypted_prod_1.0.7-620b71c.bin
> > > > > 7cf57460
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > ## Fill index html with your own version
> > > > > Fill the field in index file as needed: [index.html](https://github.com/kioipp/bose_earbuds_firmware/blob/main/index.xml)
> > > > 
> > > > 
> > > > It seems that you can't use the bose updater application to install the latest 2.0.7 firmware.
> > > 
> > > 
> > > 
> > > * Merge 2.0.7 index content;
> > > * Use official index content;
> > > 
> > > The two ways could install the latest firmware either.
> > 
> > 
> > I tried. the log says "update failed". however the 1.0.7 firmware can be installed.
> 
> I found there is a error in the official index , the length of the 2.07 firmware is 6534306, but the index shows it 6350682 as it is the length of 1.27. So that is why it does't work.

The info you provided is very helpful! Now it can be updated. By the way, the original CRC value is also incorrect.

**Comment by Canawan** [comment]
Hello sir, I have a bose quietcomfort earbud and want to downgrade the firmware, can you make a more detailed guide, because I'm not very good with technology
